from .CrossEntropy import CrossEntropyLoss2d
from .FitNet import HintLoss
from .FT import FactorTransfer
from .JSDiv import JSDivergenceLoss
from .KLDiv import KLDivergenceLoss
from .KDSVD import KDSVD
from .NST import NSTLoss
from .PKT import PKT
from .RKD import RKDLoss
from .SP import Similarity
from .VID import VIDLoss
from .MSELoss import MSELoss